### PR TITLE
Fix unecessary quote change for attribute value in Jinja

### LINKED ISSUE #55: Unecessary quote change for attribute value
Hi :wave: 

In Jinja, this is totally ok to use double quote inside an interpolation that is inside a double quoted string. 
Currently, this get's reformatted like that (which is required for html, but conflict with the chosen quote style -- [Double](https://github.com/g-plane/markup_fmt/blob/main/docs/config.md#quotes) in this case). 

```diff
-<div data-content="{% if status == "active" %}Id like it{% endif %}"></div>
+<div data-content='{% if status == "active" %}Id like it{% endif %}'></div>
```

This issue is quite common when using [jinja filters](https://jinja.palletsprojects.com/en/3.0.x/templates/#list-of-builtin-filters)
```jinja
<input class="form-submit" type="submit" value="{{ initial|default("True") }}"/>

{% for row in [1,2] %}
    <li class="{{ loop.cycle("odd", "even") }}">{{ row }}</li>
{% endfor %}
```

I was thinking maybe we should not switch quote style for Jinja when it would conflit with the selected quote style and assume this is intentional ? (The best thing would be to switch the quotes inside interpolations in that case but it seems a bit complicated to achieve)

What do you think ? I'll be happy to help submit a patch

### PR DESCRIPTION
**Pull request by UnknownPlatypus**
Fixes #55

Review commit per commit is advised, I did some minor refactoring work that will make more sense reviewed that way.

The actual change fixing the issue for me is quite minimal (see the [last commit](https://github.com/g-plane/markup_fmt/commit/81fd31babaf351213ecbf4e0dc24f076cd53f093)). Basically special casing jinja to respect the configured quote style even if there is a quote inside the value (because Jinja allows that and will parse it correctly).

### CODE REVIEW

File: markup_fmt/src/printer.rs [hunk 1]
```diff
@@ -2414,3 +2396,36 @@ where
             state,
         )))
 }
+
+/// Computes the appropriate quote character (single or double) to use for an attribute value.
+///
+/// This will try to respect the configured `quotes` but might change it
+/// to ensure the result is valid html.
+fn compute_attr_value_quote<'s, E, F>(
+    attr_value: &Cow<str>,
```
Comment (g-plane) [inline markup_fmt/src/printer.rs:2405]:
```suggestion
    attr_value: &'s str,
```

File: markup_fmt/src/printer.rs [hunk 2]
```diff
@@ -2414,3 +2396,36 @@ where
...
+            Doc::text(quote.to_string())
+        } else if let Quotes::Double = ctx.options.quotes {
+            Doc::text("\"")
+        } else {
+            Doc::text("'")
+        }
+    } else if has_double && !matches!(ctx.language, Language::Jinja) {
+        Doc::text("'")
+    } else if has_single && !matches!(ctx.language, Language::Jinja) {
+        Doc::text("\"")
```
Comment (g-plane) [inline markup_fmt/src/printer.rs:2425]: These two branches can be merged to avoid checking language twice.

File: markup_fmt/tests/fmt/jinja/attributes/mixed-quotes/mixed-quotes.jinja [hunk 3]
```diff
@@ -0,0 +1,35 @@
...
+<!-- Should keep '' if quotes = "single" -->
+
+<div data-content='{% if status == 'active' %}Yay{% endif %}'></div>
+<input value='{{ initial|default('True') }}'/>
+<input value='{{ field.value|default('', true) }}'/>
+<button class='{{ ['btn_class', 'btn-expand']|join(' ') }}'></button>
+{% for row in [1,2] %}
+    <li class='{{ loop.cycle('odd', 'even') }}'>{{ row }}</li>
+{% endfor %}
+
```
Comment (g-plane) [inline markup_fmt/tests/fmt/jinja/attributes/mixed-quotes/mixed-quotes.jinja:35]: Unexpected trailing empty line.

**Review by g-plane — COMMENTED** [review]
Thanks!

**Review by g-plane — APPROVED** [review]
